# Header

menu:
  主页: /
  相册: /photos
  归档: /archives
# SubNav
subnav:
  github: "https://github.com/xh747364"
  #qq: "1085690610"
  #weixin: "xh308922952"
  #weibo: "http://weibo.com/litten225"
  #rss: /atom.xml
  #psn: "#"
  #zhihu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  #mail: "mailto:litten225@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

#rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root:

# Content
excerpt_link: 'more'
show_all_link: '展开全文'
fancybox: true
mathjax: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 0
reward_wording: '谢谢你请我吃糖果'
alipay: /assets/img/alipay.jpg
weixin: /assets/img/weixin.jpg

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# 是否在新窗口打开链接
open_in_new: true

# Miscellaneous
baidu_analytics: 'a30844fa2bcbce0a9e001fe06cefeddf'
google_analytics: false
favicon: /assets/img/favicon.ico

#你的头像url
avatar: /assets/blogImg/litten.png

#是否开启分享
share_jia: true

mobile:
  social: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus 不需要使用某项，直接设置值为false，或注释掉
#请参考wiki：

#1、多说
#duoshuo: "litten-hexo"

#2、网易云跟帖
#wangyiyun: '2dba06fbf8d24c13915ea6c6aa7183b1'

#3、畅言
#changyan_appid: 'cysX3aGWt'
#changyan_conf: 'prod_1dcda447175aada96edcdb7e412338fa'

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
#disqus: false

#5、Gittakl
gitalk:
  enable: true #是否开启
  githubID: xh747364 #你的Github用户名
  repo: xh747364.github.io #Github仓库名称
  ClientID: 3c3f0c545dfcee251250 #创建的Application ClientID
  ClientSecret: bbb387f945391e28f62c0aa5485626691dafb83f #创建的Application ClientSecret
  adminUser: xh747364 # 评论初始化账户(GitHub ID)
  distractionFreeMode: true # 是否开启分心自由模式 也就是免打扰
#6、Gitment
#gitment:
    #owner: 'xh747364'                  #你的 GitHub ID
    #repo: 'xh747364.github.io'     #存储评论的 repo
    #client_id: '3c3f0c545dfcee251250'     #client ID
    #client_secret: 'bbb387f945391e28f62c0aa5485626691dafb83f'

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友情链接'
  aboutme: '关于我'

friends:
    羽毛: http://scuzivn.top/
		冯金琪: https://www.fengjinqi.com/
    南岸南: https://www.nanbk.com/

aboutme: 即许一人以偏爱，<br>愿尽余生之慷慨。
